module.exports.discriptors = [
    'Amazing',
    'Cool',
    'Cold',
    'Hot',
    'Winter',
    'Tasty',
    'Breathtaking',
    'Fabulous',
    'Fantastic',
    'Great',
    'Best',
    'Only',
    'Insane',
    'Frightening',
    'Cool',
    'Cold',
    'Hot',
    'Winter',
    'Tasty',
    'Terrifying',
    'Terrific'
];

module.exports.cupProviders = [
    'Starbucks',
    'RoadCup',
    'Barnez',
    'Dunkin',
    'Mankin',
    'Java Cup',
    'Road Coffee',
    'Musha',
    'One Drip',
    'Starbucks',
    'RoadCup',
    'Barnez',
    'Dunkin',
    'Mankin',
    'Java Cup',
    'Road Coffee',
    'Musha',
    'One Drip',
    'SomethingCool',
    'BestCoffee'
]